name: niden.net

author: "Nikolaos Dimopoulos"
description: "Personal blog of Nikolaos (Nikos) Dimopoulos. Boldly goes where no other coder has gone before.... and other ramblings"
keywords: "php, phalcon, phalcon php, php framework, faster php framework"
generator: "Github Pages"
avatar: https://avatars3.githubusercontent.com/u/1073784?v=4

social:
  email:
  facebook:
  github: niden
  rss: niden
  twitter:

disqus:
google_analytics: UA-26971391-1
url: https://niden.net
baseurl: "/"

paginate: 5
paginate_path: "/page-:num"
permalink: /post/:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

sass:
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
