name: niden.net

author: 'Nikolaos Dimopoulos'
description: 'Personal blog of Nikolaos (Nikos) Dimopoulos. Boldly goes where no other coder has gone before.... and other ramblings'
keywords: 'php, phalcon, phalcon php, php framework, faster php framework'
avatar: https://avatars3.githubusercontent.com/u/1073784?v=4

url: https://niden.net

social:
  email:
  github: niden
  rss: niden

google_analytics: 'UA-26971391-1'

paginate: 5
paginate_path: '/page-:num'
permalink: /post/:title/

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-archives

include:
  - _pages
  - _redirects

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/:month/'
    day: '/archive/:year/:month/:day/'
    tag: '/tag/:name/'
#    category: '/category/:name/'

sass:
  style: compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - .github
  - .jekyll-cache
  - .gitignore
  - .jekyll-metadata
  - .ruby-version
  - _config.yml
  - _redirects
  - vendor
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - serve
  - color_admin_v5.1.5
