# For local development only.

services:
    niden-net-blog:
        container_name: niden-net-blog
        hostname: niden-net-blog
        image: bretfisher/jekyll-serve
        volumes:
            - .:/site
