name: CI

on:
  - push
  - pull_request

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - '2.6.2'

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1.118.0
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install blog dependencies using Ruby ${{ matrix.ruby }}
        run: |
          gem install bundler
          bundle install --jobs "$(getconf _NPROCESSORS_ONLN)" --retry 3
      - name: Build static files
        run: bundle exec jekyll build -d _site

      - name: Test
        run: bundle exec htmlproofer ./_site --check_external_hash --check_favicon --check_html
        
        
        
